import type { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * @description The table that makes refresh tokens revocable.
 *
 * Generated by `migration:generate` from `RefreshTokenEntity` rather than written by
 * hand, deliberately. The two foreign key constraints carry TypeORM's hashed names;
 * inventing readable ones would make `schema:log` report drift on every run, because
 * TypeORM compares against the names it would have produced itself.
 *
 * Three columns carry the whole security design:
 *
 * - `tokenHash` is unique, which is what lets rotation be a compare-and-swap:
 *   `UPDATE ... WHERE "tokenHash" = $1 AND "revokedAt" IS NULL RETURNING ...` either
 *   claims the token or returns nothing, with no window in between for a second
 *   request to claim it too.
 * - `revokedAt` is how a token dies. Not a soft delete — this table must stay fully
 *   visible, since a spent token that has vanished cannot be recognised when it is
 *   replayed.
 * - `familyId` groups every token descended from one login, so a detected replay can
 *   revoke the entire chain instead of only the link that was reused.
 *
 * `ON DELETE CASCADE` on `userId` means a hard-deleted user takes their sessions with
 * them. `users` uses soft delete on the normal path, so the cascade does not fire
 * there — sessions of a soft-deleted user have to be revoked explicitly.
 */
export class AddRefreshTokens1785855635621 implements MigrationInterface {
  name = 'AddRefreshTokens1785855635621';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TABLE "refresh_tokens" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tokenHash" character(64) NOT NULL, "userId" uuid NOT NULL, "familyId" uuid NOT NULL, "expiresAt" TIMESTAMP WITH TIME ZONE NOT NULL, "revokedAt" TIMESTAMP WITH TIME ZONE, "replacedById" uuid, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_7d8bee0204106019488c4c50ffa" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `CREATE INDEX "IDX_refresh_tokens_family" ON "refresh_tokens"  ("familyId") `,
    );
    await queryRunner.query(
      `CREATE INDEX "IDX_refresh_tokens_user" ON "refresh_tokens"  ("userId") `,
    );
    await queryRunner.query(
      `CREATE UNIQUE INDEX "UQ_refresh_tokens_token_hash" ON "refresh_tokens"  ("tokenHash") `,
    );
    await queryRunner.query(
      `ALTER TABLE "refresh_tokens" ADD CONSTRAINT "FK_610102b60fea1455310ccd299de" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "refresh_tokens" ADD CONSTRAINT "FK_2ed2be3b03a9eebf7123f2a9412" FOREIGN KEY ("replacedById") REFERENCES "refresh_tokens"("id") ON DELETE SET NULL ON UPDATE NO ACTION`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE "refresh_tokens" DROP CONSTRAINT "FK_2ed2be3b03a9eebf7123f2a9412"`,
    );
    await queryRunner.query(
      `ALTER TABLE "refresh_tokens" DROP CONSTRAINT "FK_610102b60fea1455310ccd299de"`,
    );
    await queryRunner.query(`DROP INDEX "public"."UQ_refresh_tokens_token_hash"`);
    await queryRunner.query(`DROP INDEX "public"."IDX_refresh_tokens_user"`);
    await queryRunner.query(`DROP INDEX "public"."IDX_refresh_tokens_family"`);
    await queryRunner.query(`DROP TABLE "refresh_tokens"`);
  }
}
